name: server deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Add permission `chmod +x` to gradle file
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew adaptor:in:web-server:bootJar

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private-key.key
          chmod 600 ~/private-key.key
      - name: Create SSH directory
        run: |
          mkdir -p ~/.ssh
      - name: Add known host
        run: |
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
          scp -P ${{ secrets.SSH_PORT }} -i ~/private-key.key adaptor/in/web-server/build/libs/web-server-0.0.1-SNAPSHOT.jar ${{ secrets.USERNAME}}@${{ secrets.HOST}}:~/src/blog/archive/
          ssh -P ${{ secrets.SSH_PORT }} -i ~/private-key.key ${{ secrets.USERNAME}}@${{ secrets.HOST }} 'ls -alh ~/src/blog/archive'
